#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 27 08:36:28 2019

@author: geraldigunawan
"""
import numpy as np
import pandas as pd

np.version.version
#%% create dictionary
d = {'name':'Geraldi','age':23,'uni':'University of Sydney'}
pd.Series(d)
#%% create Series
s = pd.Series([1,2,3,4.0,5,6,7], index=['a','b','c','d','e','f','g'])
s
'g' in s
#%%
s.dtype
#%%
s2 = pd.Series(np.random.randint(5, size = 5))
s2
#%%
s2[1]
#%%
s3 = pd.Series(np.array(['a','b','c']), index=['x','y','z'])
s3
#%%
s4 = pd.Series({'x':'Geraldi','y':23,'z':'University of Sydney'})
s4
#%%
df = pd.DataFrame({'id':s3,'info':s4})
df